# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Yumtumexpress

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_fa838a563984480cb15ceda2b98be79b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_820b4dd5d2fc47f4bd58a56a9c51cb32 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_fa838a563984480cb15ceda2b98be79b }}/azure-app-service/windows/parkingpage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Yumtumexpress'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7dc12ef353084ca1a6de51d0eef1d02c }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_fa838a563984480cb15ceda2b98be79b }}/azure-app-service/windows/parkingpage:${{ github.sha }}'